### ISSUE TITLE
Problems at compile

### ISSUE THREAD

**Issue by jpereiranet** [luca-penasa/Apero2Meshlab#2]
Hello:
I was trying to compile the last code of micmac (rev2578) with Apero2Meshlab and get the next error:

[ 98%] Building CXX object src/CBinaires/CMakeFiles/mm3d.dir/mm3d.cpp.o
micmac/src/CBinaires/mm3d.cpp: En la función ‘const std::vector<cMMCom>& getAvailableCommands()’:
/micmac/src/CBinaires/mm3d.cpp:181:46: error: ‘Apero2Meshlab_main’ no se declaró en este ámbito
make[2]: **\* [src/CBinaires/CMakeFiles/mm3d.dir/mm3d.cpp.o] Error 1
make[1]: **\* [src/CBinaires/CMakeFiles/mm3d.dir/all] Error 2
make[1]: **\* Se espera a que terminen otras tareas....
Scanning dependencies of target SaisieQT

And the compilation ends with a error.
Thanks for any advance!

best wishes

**Comment by luca-penasa** [comment]
do the patch applied well or you got some errors? 
Or maybe you pulled a new revision from the repository that did not merged correctly?

It is some time I am not using it, I'll try to see if the patch still works.
I would suggest you to reset completely your working copy of culture3d and then re-apply the patch and see if it works...

I'll try to check if it still works with last revision of micmac

Thanks for the feedback...

I should definitively ask micmac guys to merge this staff with the main developing branch

**Comment by jpereiranet** [comment]
Thanks for the advance.

I tried again, with a fresh source code. I am using the code from http://logiciels.ign.fr/?Telechargement,20 rev2578, not the SVN.

The patch seems run fine, i get the next output:

install_patch.sh: 12: install_patch.sh: [[: not found
install_patch.sh: 18: [: /micmac: unexpected operator
install_patch.sh: 28: install_patch.sh: [[: not found
Copying files
CPP_Apero2Meshlab.cpp into /micmac/src/uti_files/
Apero2Meshlab.c into /micmac/src/CBinaires/
Patching other files
patching file include/general/arg_main.h
Hunk #1 succeeded at 487 (offset 53 lines).
patching file src/CBinaires/CMakeLists.txt
patching file src/CBinaires/mm3d.cpp
Hunk #1 succeeded at 178 with fuzz 1 (offset 10 lines).

Seems there are some errors at beginning, but look a syntax problem by not passing the path as a parameter.

But, now i get other different error  during compilation:

Linking CXX executable mm3d
CMakeFiles/mm3d.dir/mm3d.cpp.o: In function `getAvailableCommands()':
mm3d.cpp:(.text+0xca7): undefined reference to`Apero2Meshlab_main(int, char*_)'
collect2: ld devolvió el estado de salida 1
make[2]: *_\* [src/CBinaires/mm3d] Error 1
make[1]: **\* [src/CBinaires/CMakeFiles/mm3d.dir/all] Error 2

Thanks!

**Comment by luca-penasa** [comment]
modified code should work. Please not that I removed the script. Just use hg import --no-commit path/to/the/patch...

tell me if it is ok
for me it works

see readme for more info

**Comment by jpereiranet** [comment]
Yes! now run fine, micmac compile without problems

Thanks
Best wishes
